<a href="https://colab.research.google.com/github/Castillo-jacqueline/Metodos-numericos-/blob/main/Factorizaci%C3%B3n_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def factorizacion_LU(A):
    """
    Realiza la factorización LU de una matriz cuadrada A.
    La matriz A se descompone en A = L * U, donde:
    - L es una matriz triangular inferior (con 1s en la diagonal principal).
    - U es una matriz triangular superior.

    Parámetros:
    A (numpy.ndarray): Matriz cuadrada de tamaño nxn.

    Retorna:
    L (numpy.ndarray): Matriz triangular inferior.
    U (numpy.ndarray): Matriz triangular superior.
    """
    n = A.shape[0]  # Tamaño de la matriz
    L = np.eye(n)   # Inicializamos L como matriz identidad
    U = A.copy()    # Copia de A para modificarla y obtener U

    for i in range(n):
        # Verificar si el pivote es cero para evitar división por cero
        if U[i, i] == 0:
            raise ValueError("El pivote es cero. Reordenar filas para continuar.")

        for j in range(i+1, n):
            # Calculamos el multiplicador
            factor = U[j, i] / U[i, i]
            L[j, i] = factor  # Guardamos el multiplicador en L
            # Restamos el múltiplo de la fila i de U a la fila j de U
            U[j, i:] -= factor * U[i, i:]

    return L, U

# Definimos la matriz de prueba
A = np.array([
    [1, 1, 0, 3],
    [2, 1, -1, 1],
    [3, -1, -1, 2],
    [-1, 2, 3, -1]
], dtype=float)

# Aplicamos la factorización LU
L, U = factorizacion_LU(A)

# Verificamos el resultado
reconstruida = np.dot(L, U)

# Mostramos los resultados
print("Matriz A:")
print(A)
print("\nMatriz L (triangular inferior):")
print(L)
print("\nMatriz U (triangular superior):")
print(U)
print("\nReconstrucción de A (L * U):")
print(reconstruida)

# Comprobamos si la matriz reconstruida es igual a la original
if np.allclose(A, reconstruida):
    print("\nLa factorización LU es correcta.")
else:
    print("\nLa factorización LU es incorrecta.")

Matriz A:
[[ 1.  1.  0.  3.]
 [ 2.  1. -1.  1.]
 [ 3. -1. -1.  2.]
 [-1.  2.  3. -1.]]

Matriz L (triangular inferior):
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

Matriz U (triangular superior):
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]

Reconstrucción de A (L * U):
[[ 1.  1.  0.  3.]
 [ 2.  1. -1.  1.]
 [ 3. -1. -1.  2.]
 [-1.  2.  3. -1.]]

La factorización LU es correcta.
