<a href="https://colab.research.google.com/github/Castillo-jacqueline/Metodos-numericos-/blob/main/Tutorial_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**
Es una librería de Python que facilita el cálculo numérico y científico, proporcionando arrays multidimensionales de alto rendimiento y funciones para operaciones matemáticas complejas, álgebra lineal, generación de números aleatorios y más.
**Elaborado Castillo Zaragoza Ximena Jacqueline***

In [2]:

# Numpy Tutorial: Funciones y Utilidades Básicas

# Importar numpy
import numpy as np

#1. Creación de Arrays en NumPy


# Crear un array a partir de una lista
array_1d = np.array([1, 2, 3, 4, 5])
print("Array 1D:", array_1d)

# Crear un array 2D (matriz)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2D:\n", array_2d)

# Crear arrays de ceros, unos y vacíos
array_zeros = np.zeros((3, 3))
print("Array de ceros:\n", array_zeros)

array_ones = np.ones((2, 3))
print("Array de unos:\n", array_ones)

array_empty = np.empty((2, 2))
print("Array vacío (valores aleatorios):\n", array_empty)

# Crear un array con valores en un rango específico
array_range = np.arange(0, 10, 2)  # de 0 a 10 con paso 2
print("Array con arange:", array_range)

# Crear un array de valores equidistantes con linspace
array_linspace = np.linspace(0, 1, 5)  # de 0 a 1 con 5 puntos
print("Array con linspace:", array_linspace)


# 2. Propiedades de los Arrays


# Obtener el número de dimensiones
print("Dimensiones de array_2d:", array_2d.ndim)

# Obtener la forma (shape) del array
print("Forma de array_2d:", array_2d.shape)

# Obtener el tamaño total (número de elementos)
print("Tamaño de array_2d:", array_2d.size)

# Obtener el tipo de datos de los elementos
print("Tipo de datos de array_1d:", array_1d.dtype)

# Cambiar el tipo de datos de un array
array_float = array_1d.astype(np.float64)
print("Array convertido a float:", array_float)

# 3. Operaciones Básicas con Arrays

# Operaciones aritméticas (se aplican a cada elemento)
array_sum = array_1d + 5
print("Sumar 5 a cada elemento:", array_sum)

array_product = array_1d * 2
print("Multiplicar cada elemento por 2:", array_product)

# Operaciones entre arrays
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
print("Suma de arrays:", array_a + array_b)
print("Producto de arrays:", array_a * array_b)

# Operaciones matemáticas
print("Seno de array_a:", np.sin(array_a))
print("Raíz cuadrada de array_a:", np.sqrt(array_a))

# Funciones de agregación
print("Suma total:", np.sum(array_a))
print("Máximo:", np.max(array_a))
print("Media:", np.mean(array_a))
print("Desviación estándar:", np.std(array_a))

# 4. Indexación y Slicing (subconjuntos de arrays)

# Indexación básica
print("Primer elemento de array_1d:", array_1d[0])

# Slicing
print("Primeros tres elementos de array_1d:", array_1d[:3])

# Indexación en arrays 2D
print("Elemento en la primera fila, segunda columna:", array_2d[0, 1])

# Slicing en arrays 2D (toda la primera fila)
print("Primera fila de array_2d:", array_2d[0, :])

# 5. Manipulación de Arrays

# Cambiar la forma (reshape)
array_reshaped = array_1d.reshape((1, 5))
print("Array reshaped (1,5):\n", array_reshaped)

# Concatenar arrays
array_concatenated = np.concatenate((array_a, array_b))
print("Arrays concatenados:", array_concatenated)

# Dividir arrays
array_split = np.split(array_concatenated, 2)
print("Array dividido:", array_split)

# Transponer un array 2D
print("Transpuesta de array_2d:\n", array_2d.T)

# 6. Generación de Números Aleatorios

# Generar un número aleatorio entre 0 y 1
random_num = np.random.rand()
print("Número aleatorio entre 0 y 1:", random_num)

# Generar un array de números aleatorios (forma 3x3)
random_array = np.random.rand(3, 3)
print("Array aleatorio 3x3:\n", random_array)

# Generar números aleatorios enteros entre 1 y 10
random_integers = np.random.randint(1, 10, size=(2, 3))
print("Array de enteros aleatorios 2x3:\n", random_integers)

# Fijar la semilla aleatoria para reproducibilidad
np.random.seed(42)
print("Número aleatorio con semilla fija:", np.random.rand())

# 7. Ejemplo de Aplicación: Operaciones de Álgebra Lineal


# Multiplicación de matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix_a, matrix_b)
print("Producto de matrices:\n", matrix_product)

# Determinante de una matriz
matrix_det = np.linalg.det(matrix_a)
print("Determinante de matrix_a:", matrix_det)

# Inversa de una matriz
matrix_inv = np.linalg.inv(matrix_a)
print("Inversa de matrix_a:\n", matrix_inv)

# Conclusión
# -------------------------------------------
# Este tutorial ha cubierto las bases de NumPy, incluyendo creación de arrays,
# operaciones aritméticas, manipulaciones y funciones de álgebra lineal. NumPy es
# una librería poderosa para la manipulación de datos y cálculo científico.

Array 1D: [1 2 3 4 5]
Array 2D:
 [[1 2 3]
 [4 5 6]]
Array de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array de unos:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array vacío (valores aleatorios):
 [[2.  1. ]
 [1.5 0.5]]
Array con arange: [0 2 4 6 8]
Array con linspace: [0.   0.25 0.5  0.75 1.  ]
Dimensiones de array_2d: 2
Forma de array_2d: (2, 3)
Tamaño de array_2d: 6
Tipo de datos de array_1d: int64
Array convertido a float: [1. 2. 3. 4. 5.]
Sumar 5 a cada elemento: [ 6  7  8  9 10]
Multiplicar cada elemento por 2: [ 2  4  6  8 10]
Suma de arrays: [5 7 9]
Producto de arrays: [ 4 10 18]
Seno de array_a: [0.84147098 0.90929743 0.14112001]
Raíz cuadrada de array_a: [1.         1.41421356 1.73205081]
Suma total: 6
Máximo: 3
Media: 2.0
Desviación estándar: 0.816496580927726
Primer elemento de array_1d: 1
Primeros tres elementos de array_1d: [1 2 3]
Elemento en la primera fila, segunda columna: 2
Primera fila de array_2d: [1 2 3]
Array reshaped (1,5):
 [[1 2 3 4 5]]
Arrays concatenados: [1 2 3 4 5 6]
Arr